# Generated by Django 4.1.7 on 2023-05-17 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Point',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('points', models.CharField(max_length=200)),
                ('close_points', models.CharField(max_length=200)),
            ],
        ),
    ]
